services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jobs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  river-ui:
    image: ghcr.io/riverqueue/riverui:latest
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/jobs

  coord:
    build:
      dockerfile: provision/hex-coord/Dockerfile
      context: .
    env_file:
      - ./cmd/hex-coord/.env
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./workspace:/workspace
  worker:
    build:
      dockerfile: provision/worker/Dockerfile
      context: .
    env_file:
      - ./cmd/coord/.env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./workspace:/workspace
